### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by taozhang0000** [THU-KEG/ADELIE#1]
Great work. Would you like to ask how to download the dataset(IEInstruct, IEFeedBack)? the link seems to be invalid at present

**Comment by kijlk** [comment]
Hello, our current model and dataset have been publicly released, and you can access the latest repository. However, please note that there may be some unhandled details in the current code which could potentially cause minor inconveniences during execution. I will address these issues soon.

**Comment by datalee** [comment]
只有英文的对吧？可以提升中文上的表现吗
